name: 'stackoverflow_analysis_aw'
version: '1.0.0'
config-version: 2

profile: 'stackoverflow_analysis_aw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  stackoverflow_analysis_aw:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table